service: lambda-express-web-adapter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1769
  environment:
    AJ_TEST: true

functions:
  express-lwa:
    handler: run.sh
    url: true
    environment:
      AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
      AWS_LWA_READINESS_CHECK_PATH: /health
    layers:
      - arn:aws:lambda:us-east-1:753240598075:layer:LambdaAdapterLayerX86:22

